# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Paolo Bietolini
email: hello@paolobietolini.xyz
description: >- # this means to ignore newlines until "baseurl:"
  Paolo Bietolini è un esperto analytics developer. 
  Questo è un blog dedicato allo sviluppo di analisi web e al tag management.
# twitter_username: username
github_username: plbtl
locale: "it-IT"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
date_format: "%Y-%m-%d"
repository: "paolobtl/blog"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Rome # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Paolo Bietolini"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Analytics Developer"
  location: "Kraków, 🇵🇱"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://paolobietolini.xyz"
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://mastodon.uno/@plbtl"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/paolobtl"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/paoloinpolonia"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-mastodon-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/paolobtl"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/paoloinpolonia"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_label: "Tabella dei contenuti"
      toc_sticky: true
      excerpt: ""
      show_date: true
      header:
        overlay_image: https://source.unsplash.com/random/1920x602/?abstract?orientation=landscape
        verlay_filter: 0.5
        caption: "Photo credit: [**Unsplash**](https://unsplash.com)"
  
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
